In [ ]:
!pip install numpy 

ERROR: Could not find a version that satisfies the requirement as (from versions: none)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for as


In [2]:
#create array using numpy 

In [12]:
#create a 1D array
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 col

array([[1, 2, 3, 4, 5]])

In [ ]:
2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
## identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# NUmpy vectorize opration 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise addition
print("Addition:",arr1 + arr2)

#element wise subration
print("subtraction:",arr1-arr2)

#element wise Multiplication
print("multiplication:",arr1*arr2)

#element wise division
print("division:",arr1/arr2)

Addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [35]:
#universal function 
arr=np.array([2,3,4,5,6])

#square root 
print(np.sqrt(arr))

#exponantial
print(np.exp(arr))

## sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [39]:
#slicing of array and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array: \n",arr)

array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
print(arr[0][1])

2


In [47]:
print(arr[1:])
print(arr[0:2,1:])


[[ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3 4]
 [6 7 8]]


In [49]:
 # modify the array elements
arr[0,0]=200
print(arr)

[[200   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [50]:
arr[1:]=100
print(arr)

[[200   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [56]:
data=np.array([1,2,3,4,5,6,7,8,9])

print(data>5)
data[data>5]
data[(data>5 )& (data<=8)]

[False False False False False  True  True  True  True]


array([6, 7, 8])